// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tupen.Backend.Data;

#nullable disable

namespace Tupen.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211151808_CreateBookingTable")]
    partial class CreateBookingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tupen.Backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Tupen.Backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 1, Gedung A",
                            IsAvailable = true,
                            Name = "Ruang Teori A1",
                            RoomNumber = "A.101"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 1, Gedung A",
                            IsAvailable = true,
                            Name = "Ruang Teori A2",
                            RoomNumber = "A.102"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 2, Gedung A",
                            IsAvailable = true,
                            Name = "Lab Komputer A1",
                            RoomNumber = "A.201"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 2, Gedung A",
                            IsAvailable = true,
                            Name = "Lab Komputer A2",
                            RoomNumber = "A.202"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 60,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 3, Gedung A",
                            IsAvailable = true,
                            Name = "Aula Mini Gedung A",
                            RoomNumber = "A.301"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 1, Gedung B",
                            IsAvailable = true,
                            Name = "Ruang Teori B1",
                            RoomNumber = "B.101"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 40,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 1, Gedung B",
                            IsAvailable = true,
                            Name = "Ruang Teori B2",
                            RoomNumber = "B.102"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 2, Gedung B",
                            IsAvailable = true,
                            Name = "Studio Gambar B1",
                            RoomNumber = "B.201"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 25,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 2, Gedung B",
                            IsAvailable = true,
                            Name = "Studio Gambar B2",
                            RoomNumber = "B.202"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 35,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 3, Gedung B",
                            IsAvailable = true,
                            Name = "Lab Komputer B3",
                            RoomNumber = "B.305"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 45,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 1, Gedung C",
                            IsAvailable = true,
                            Name = "Ruang Teori C1",
                            RoomNumber = "C.101"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 45,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 1, Gedung C",
                            IsAvailable = true,
                            Name = "Ruang Teori C2",
                            RoomNumber = "C.102"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 20,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 2, Gedung C",
                            IsAvailable = true,
                            Name = "Ruang Rapat C1",
                            RoomNumber = "C.201"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 20,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 2, Gedung C",
                            IsAvailable = true,
                            Name = "Ruang Rapat C2",
                            RoomNumber = "C.202"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 100,
                            CreatedAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lantai 3, Gedung C",
                            IsAvailable = true,
                            Name = "Aula Serbaguna",
                            RoomNumber = "C.301"
                        });
                });

            modelBuilder.Entity("Tupen.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tupen.Backend.Models.Booking", b =>
                {
                    b.HasOne("Tupen.Backend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tupen.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
